parameters:
    loyality_mapping:
        maxAmount:
            - 1000
            - 2000
            - 4000
            - 8000
            - 10000
            - 12000
        maxTerm:
            - 3
            - 7
            - 14
            - 21
            - 30
            - 35
        interestRate:
            - 0.018
            - 0.016
            - 0.014
            - 0.012
            - 0.01
            - 0.008
