<?php

namespace AppBundle\Repository;

/**
 * RegistrationStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationStepRepository extends \Doctrine\ORM\EntityRepository
{
}
